name: CI
on:
  push:
    branches:
    - master
jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Version
      uses: paulhatch/semantic-version@v2
      with:
        # The branch to count commits on
        branch: "master"
        # The prefix to use to identify tags
        tag_prefix: ""
        # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
        major_pattern: "(MAJOR)"
        # Same as above except indicating a minor change
        minor_pattern: "(MINOR)"
        # A string to determine the format of the version output
        format: "${major}.${minor}.${patch}"
      id: versioning
    
    - name: split upm branch
      run: |
        git subtree split --prefix="$PKG_ROOT" --branch upm
        git tag $steps.versioning.outputs.version upm
        git push origin upm --tags
      env:
        PKG_ROOT: Assets/SO Architecture

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: $steps.versioning.outputs.version
        release_name: Release $steps.versioning.outputs.version
        draft: false
        prerelease: false
